---
title: "Josephine_WIP"
author: "Josephine Wright"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(janitor)
library(RColorBrewer)
library(ggplot2)
library(paletteer)
library(ggmap)
library(patchwork)
library(ggdensity)
library(paletteer)
library(RColorBrewer)
```

```{r}
setwd("~/Desktop/BIS15L_W2026_Group-8/rbird")
```

Data
```{r}
sample_data <- read_csv("sample_data.csv") %>%
  clean_names()
```
```{r}
species_data <- read_csv("species_data.csv") %>%
  clean_names()
```
```{r}
total_data <- read_csv("total_data.csv") %>%
  clean_names()
```

Removing data from total_data where the only information is sampling_event_identifier
```{r}
#total_data <- total_data %>%
#  filter(!is.na(common_name))
```

How many bird species are represented by the data?
```{r}
total_data %>% 
  distinct(common_name) %>% 
  count()
```

Top five bird observations between 2019 and 2021 (total)
```{r}
top_five_total <- total_data %>%
  filter(year_y %in% c(2019, 2020, 2021)) %>% 
  group_by(common_name) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  slice_head(n = 5)
top_five_total
```

```{r}
top_five_total %>% 
ggplot(aes(x = common_name, y = count, fill = common_name)) +
  geom_bar(stat = "identity") +
  coord_flip()+
  scale_fill_brewer(palette = "Dark2")+
  labs(title = "Top Five Birds with Most Observations",
       x = "Common Name",
       y = "Count of Observations",
       fill="Common Name") +
  theme(plot.title = element_text(size = 15),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        legend.position = "none")
```

Top five birds with most observations per each year
```{r}
top_five <- total_data %>%
  filter(year_y %in% c(2019, 2020, 2021)) %>% 
  group_by(year_y, common_name) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  slice_head(n = 5)
top_five
```

```{r}
top_five %>%
  ggplot(aes(x = year_y, y = count, fill = common_name)) +
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip()+
  scale_fill_brewer(palette = "Dark2")+
  labs(title = "Top Five Birds with Most Observations",
       x = "Year",
       y = "Count of Observations",
       fill="Common Name") +
  theme(plot.title = element_text(size = 15),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14))
```





